import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics Meta */}
        {process.env.NEXT_PUBLIC_GA_ID && (
          <meta name="google-analytics-id" content={process.env.NEXT_PUBLIC_GA_ID} />
        )}
        
        {/* Google AdSense Meta */}
        {process.env.NEXT_PUBLIC_ADSENSE_ID && (
          <meta name="google-adsense-account" content={process.env.NEXT_PUBLIC_ADSENSE_ID} />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* Google Services ClientSide Scripts */}
        <Script id="google-services" strategy="afterInteractive">
          {`
            // 初始化Cookie同意机制
            window.initCookieConsent = function() {
              // 创建Cookie同意对话框
              const createConsentDialog = () => {
                const consentKey = 'cookie_consent';
                const hasConsent = localStorage.getItem(consentKey);
                
                if (hasConsent) return;
                
                const dialog = document.createElement('div');
                dialog.className = 'fixed bottom-0 left-0 right-0 bg-white p-4 shadow-lg z-50';
                dialog.innerHTML = \`
                  <div class="max-w-6xl mx-auto">
                    <h3 class="text-lg font-bold mb-2">Cookie 设置</h3>
                    <p class="mb-4">
                      我们使用cookie来增强您的浏览体验，提供个性化内容和广告，以及分析我们的流量。
                    </p>
                    <div class="flex flex-wrap gap-2">
                      <button id="cookie-reject" class="px-4 py-2 bg-gray-200 hover:bg-gray-300 rounded">
                        拒绝
                      </button>
                      <button id="cookie-accept" class="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded">
                        接受
                      </button>
                    </div>
                  </div>
                \`;
                
                document.body.appendChild(dialog);
                
                // 添加事件处理
                document.getElementById('cookie-accept').addEventListener('click', () => {
                  localStorage.setItem(consentKey, JSON.stringify({
                    analytics: true,
                    advertising: true,
                    timestamp: Date.now()
                  }));
                  dialog.remove();
                  initGoogleServices(true, true);
                });
                
                document.getElementById('cookie-reject').addEventListener('click', () => {
                  localStorage.setItem(consentKey, JSON.stringify({
                    analytics: false,
                    advertising: false,
                    timestamp: Date.now()
                  }));
                  dialog.remove();
                });
              };
              
              setTimeout(createConsentDialog, 1000);
            };
            
            // 初始化Google服务
            window.initGoogleServices = function(allowAnalytics, allowAds) {
              const gaId = document.querySelector('meta[name="google-analytics-id"]')?.getAttribute('content');
              const adsenseId = document.querySelector('meta[name="google-adsense-account"]')?.getAttribute('content');
              
              // 初始化Google Analytics
              if (allowAnalytics && gaId) {
                const gaScript = document.createElement('script');
                gaScript.async = true;
                gaScript.src = \`https://www.googletagmanager.com/gtag/js?id=\${gaId}\`;
                document.head.appendChild(gaScript);
                
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', gaId);
              }
              
              // 初始化Google AdSense
              if (allowAds && adsenseId) {
                const adScript = document.createElement('script');
                adScript.async = true;
                adScript.crossOrigin = 'anonymous';
                adScript.src = \`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=\${adsenseId}\`;
                document.head.appendChild(adScript);
              }
            };
            
            // 检查已有的Cookie同意并初始化服务
            (function() {
              const consentKey = 'cookie_consent';
              try {
                const consent = localStorage.getItem(consentKey);
                if (consent) {
                  const { analytics, advertising } = JSON.parse(consent);
                  initGoogleServices(analytics, advertising);
                } else {
                  // 没有同意记录，显示对话框
                  window.initCookieConsent();
                }
              } catch (e) {
                console.error('Error checking consent:', e);
                window.initCookieConsent();
              }
            })();
          `}
        </Script>
      </body>
    </html>
  );
}
